steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/careershot:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/careershot:latest'
      - '.'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'careershot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/careershot:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'

# Push the container image to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/careershot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/careershot:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1600s