steps:
  # Build the container image with caching
  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
    - '-t' 
    - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'
    - '--cache-from'
    - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'
    - '.'
    timeout: 1200s

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest']

  # Deploy to Cloud Run with optimal settings for us-central1
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '$_SERVICE_NAME'
    - '--image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
    - '--region=$_REGION'
    - '--project=$PROJECT_ID'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=3000'
    - '--memory=2Gi'
    - '--cpu=2'
    - '--timeout=900'
    - '--max-instances=10'
    - '--min-instances=0'
    - '--concurrency=80'
    - '--execution-environment=gen2'
    - '--service-account=987917562718-compute@developer.gserviceaccount.com'
    timeout: 900s

# Substitutions for flexibility
substitutions:
  _SERVICE_NAME: careershot
  _REGION: us-central1

# Build configuration
timeout: 2400s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  disk_size_gb: 100
  substitution_option: ALLOW_LOOSE